name: AEMY Catalyze Trigger

on:
  schedule:
    - cron: '0 9 * * *'  # Runs every day at 9 AM UTC
  workflow_dispatch:
  pull_request:       # triggers on PR creation/updates

jobs:
  trigger-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Set Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    steps:
      - name: Create GitHub Issue
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const today = new Date().toISOString().split('T')[0];
            const issueTitle = `AEMY Catalyze - ${today}`;
            const issueBody = `Catalyze https://main--aem-boilerplate--adobe.aem.page/.`;

            const response = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['aemy-go', 'aemy-help', 'aemy-merge']
            });

            console.log(`Created issue: ${response.data.html_url}`);

      - name: Save issue number
        run: echo "${{ env.issue_number }}" > issue_number.txt

      - uses: actions/upload-artifact@v4
        with:
          name: issue-number
          path: issue_number.txt

      - name: Post Slack Message - Started
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        run: |
          curl -X POST https://slack.com/api/chat.postMessage \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H "Content-type: application/json" \
            --data '{
              "channel": "'"$SLACK_CHANNEL_ID"'",
              "text": "🚀 *AEMY Catalyze E2E test started* for ${{ steps.date.outputs.date }}.\n🔗 <https://github.com/aemdemos/sta-aem-boilerplate/issues/${{ env.issue_number }}|View Issue>"
            }'
