name: Daily E2E Test

on:
  schedule:
    - cron: '0 12 * * *'  # every day at 12:00 UTC
  workflow_dispatch:
  pull_request:

permissions:
  issues: write
  contents: read

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Issue
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const today = new Date().toISOString().split('T')[0];
            const issueTitle = `AEMY Catalyze - ${today}`;
            const issueBody = `Catalyze https://main--aem-boilerplate--adobe.aem.page/.`;

            const response = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['aemy-go', 'aemy-help', 'aemy-merge']
            });
            core.setOutput('issue_url', response.data.html_url);
            core.setOutput('issue_title', response.data.title);

            console.log(`Created issue: ${response.data.html_url}`);
      - name: Post Slack message for new issue
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "text": "*E2E Test Started* :rocket:\nIssue created: <${{ steps.create_issue.outputs.issue_url }}|${{ steps.create_issue.outputs.issue_title }}>"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}