name: Daily E2E Test

on:
  schedule:
    - cron: '0 12 * * *'  # every day at 12:00 UTC
  workflow_dispatch:
  pull_request:

permissions:
  issues: write
  contents: read

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Issue
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const today = new Date().toISOString().split('T')[0];
            const issueTitle = `AEMY Catalyze - ${today}`;
            const issueBody = `Catalyze https://main--aem-boilerplate--adobe.aem.page/.`;

            const response = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['aemy-go', 'aemy-help', 'aemy-merge']
            });
            core.setOutput('issue_url', response.data.html_url);
            core.setOutput('issue_title', response.data.title);

            console.log(`Created issue: ${response.data.html_url}`);
      - name: Debug Slack secrets
        run: |
          echo "Checking if SLACK_CHANNEL_ID is set..."
          if [ -z "${{ secrets.SLACK_CHANNEL_ID }}" ]; then
            echo "❌ SLACK_CHANNEL_ID is empty or not set"
          else
            echo "✅ SLACK_CHANNEL_ID is set (length: ${#SLACK_CHANNEL_ID})"
            echo "Channel ID starts with: ${SLACK_CHANNEL_ID:0:1}"
          fi
          
          echo "Checking if SLACK_BOT_TOKEN is set..."
          if [ -z "${{ secrets.SLACK_BOT_TOKEN }}" ]; then
            echo "❌ SLACK_BOT_TOKEN is empty or not set"
          else
            echo "✅ SLACK_BOT_TOKEN is set"
          fi
        env:
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Post Slack message for new issue
        if: always()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "text": "* Experience Catalyst E2E Test Started* :rocket:\nIssue created: <${{ steps.create_issue.outputs.issue_url }}|${{ steps.create_issue.outputs.issue_title }}>"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}