name: Notify Slack of Failed Subissues

on:
  issues:
    types: [labeled, edited, closed]

jobs:
  notify-failed-subissues:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Find subissues with aemy-failed label
        id: find_failed
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get timeline events for the current issue
            const events = await github.rest.issues.listEventsForTimeline({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              per_page: 100
            });

            // Find linked issues (subissues)
            const subissueUrls = [];
            for (const event of events.data) {
              if (event.event === 'connected' && event.subject && event.subject.url) {
                subissueUrls.push(event.subject.url);
              }
            }

            // Check each subissue for the aemy-failed label
            const failedSubissues = [];
            for (const url of subissueUrls) {
              const subissue = await github.request(`GET ${url}`);
              const hasFailed = subissue.data.labels.some(label => label.name === 'aemy-failed');
              if (hasFailed) {
                failedSubissues.push(subissue.data.html_url);
              }
            }

            // Output the failed subissue URLs
            core.setOutput('failed_urls', failedSubissues.join('\n'));
      - name: Get Slack thread_ts from issue comments
        id: get_thread_ts
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const threadComment = comments.data.reverse().find(c => c.body.startsWith('Slack thread_ts: '));
            if (threadComment) {
              const thread_ts = threadComment.body.replace('Slack thread_ts: ', '').trim();
              core.setOutput('thread_ts', thread_ts);
            }
      - name: Post failed subissues to Slack
        if: steps.find_failed.outputs.failed_urls != ''
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "Subissues with *aemy-failed* label:\n${{ steps.find_failed.outputs.failed_urls }}",
              "thread_ts": "${{ steps.get_thread_ts.outputs.thread_ts }}"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} 